services:
  - type: web
    name: dark-shadow-ctf
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python advanced_ctf_web.py
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: "False"
    plan: free
